language: en

pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "SklearnIntentClassifier"
  - name: "CRFEntityExtractor"
    features: [ ["low", "title", "upper"],
      [
          "bias",
          "low",
          "prefix5",
          "prefix2",
          "suffix5",
          "suffix3",
          "suffix2",
          "upper",
          "title",
          "digit",
          "pattern",
          "ner_features",
      ],
     ["low", "title", "upper"]]

  - name: "EntitySynonymMapper"

policies:
  - name: "examples.restaurantbot.policy.RestaurantPolicy"
    batch_size: 100
    epochs: 100
    validation_split: 0.2
  - name: MemoizationPolicy
  - name: MappingPolicy
